### ISSUE TITLE
Download translations doesn't work on version 1.1.0

### ISSUE THREAD

**Issue by n0vah** [crowdin/android-studio-plugin#35]
After upgrading to version 1.1.0, when I try to download translations, the message "Crowdin: Translations successfully downloaded" appears, but translations are not downloaded.
On version 1.0.0 everything works fine.

**Comment by andrii-bodnar** [comment]
Hi @n0vah,
could you please share your `crowdin.properties` file content? (without credentials, of course)

**Comment by n0vah** [comment]
project-id=
api-token=
disable-branches=true
auto-upload=false

**Comment by andrii-bodnar** [comment]
@n0vah, just checked your configuration on the test project and can't reproduce.

Could you please clarify "translations are not downloaded" means? Files with translations don't appear in the Android Studio Project or some translations weren't added to the existing files?

Also, please check API Calls History in the Crowdin Project settings if there any errors.

**Comment by n0vah** [comment]
I checked the API call history and all API calls were successful.
New translation files don't appear and new translations don't appear in existing files.

**Comment by andrii-bodnar** [comment]
@n0vah , thanks. Also, it will be helpful to reproduce the bug if you could provide us some information about the localization files hierarchy in your project.

**Comment by n0vah** [comment]
app/src/main/res/values-es
app/src/main/res/values-de
app/src/main/res/values-fr
...

**Comment by andrii-bodnar** [comment]
Hi, @n0vah. Could you please also provide your project ID? If you don't want to post it here, you can contact us via this form - https://crowdin.com/contacts.

**Comment by n0vah** [comment]
391541

**Comment by andrii-bodnar** [comment]
@n0vah still can't reproduce. What is your OS and Android Studio version?

**Comment by n0vah** [comment]
Android Studio 4.0
macOS Catalina 10.15.5 (19F101)

**Comment by andrii-bodnar** [comment]
@n0vah, attaching the test project - [testProject.zip](https://github.com/crowdin/android-studio-plugin/files/4736257/testProject.zip)

Try to reproduce the problem on this project and describe details of how you do that. 

Are there differences with your project? Maybe your project containing other modules with `strings.xml` files?

**Comment by n0vah** [comment]
It also doesn't work on your test project (version 1.0.0 works fine, but 1.1.0 doesn't work).
I also tried to use this plugin on another MacBook and another project, but it also didn't work on it.

**Comment by andrii-bodnar** [comment]
@n0vah try to use `File` > `Reload All from disk` after translations downloading.

**Comment by n0vah** [comment]
I've tried this before, it didn't help.

**Comment by n0vah** [comment]
Also I found another bug in this version 1.1.0:
I have build variants stageDebug, stageRelease, prodRelease, ...
And for build variants stageDebug, stageRelease I've created separate strings.xml files which contains one string "app_name" (paths: app/src/stageRelease/res/values/strings.xml, app/src/stageDebug/res/values/strings.xml )
And twice it happened that after clicking on "Upload source" the plugin uploaded strings.xml with one line from stageRelease and all translations were erased.

**Comment by andrii-bodnar** [comment]
Probably it's the multiple modules problem https://github.com/crowdin/android-studio-plugin/issues/3. Also, it might be related to the issue https://github.com/crowdin/android-studio-plugin/issues/36.

---

Our QA team just found the reason why translations don't appear in the project. 

> app/src/main/res/values-es

Default translations placeholder - `%android_code%`. You are using placeholder `%two_letters_code%` pattern for translations and it's exported from Crowdin with these codes. The old version (1.0.0) contained a bug - placeholders were not validated correctly. In 1.1.0 it was fixed and now default `%android_code%` don't match downloaded `%two_letters_code%` (definitely, we need to add some notification with a warning). 

For version 1.1.0 you need to override default pattern:

```
files.source=/app/src/main/res/values/strings.xml
files.translation=/app/src/main/res/values-%two_letters_code%/%original_file_name%
```

**Comment by n0vah** [comment]
I added files.source and files.translation to crowding.properties, but it didn't help (at least, Download translations still doesn't work, Upload source I didn't check)

**Comment by andrii-bodnar** [comment]
@n0vah, also, try to change your Crowdin file settings export pattern to `/app/src/main/res/values-%two_letters_code%/%original_file_name%`

**Comment by n0vah** [comment]
It helped, thanks.
And files.source also helped with issue of uploading source.
